const blockHeight = 30;
const blockWidth = 30;
const offset = 10;
const arenaHeight = 620;
const arenaWidth = 320;
const rowCount = (arenaHeight - (offset * 2))/blockHeight;
const columnCount = (arenaWidth - (offset * 2))/blockHeight;
const arenaCanvas = document.querySelector(".arena");
const arenaContext = arenaCanvas.getContext("2d");
